# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import safety_pb2 as safety__pb2


class SafetyServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckText = channel.unary_unary(
            "/safety.SafetyService/CheckText",
            request_serializer=safety__pb2.SafetyRequest.SerializeToString,
            response_deserializer=safety__pb2.SafetyResponse.FromString,
        )
        self.Health = channel.unary_unary(
            "/safety.SafetyService/Health",
            request_serializer=safety__pb2.HealthCheckRequest.SerializeToString,
            response_deserializer=safety__pb2.HealthCheckResponse.FromString,
        )


class SafetyServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CheckText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SafetyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CheckText": grpc.unary_unary_rpc_method_handler(
            servicer.CheckText,
            request_deserializer=safety__pb2.SafetyRequest.FromString,
            response_serializer=safety__pb2.SafetyResponse.SerializeToString,
        ),
        "Health": grpc.unary_unary_rpc_method_handler(
            servicer.Health,
            request_deserializer=safety__pb2.HealthCheckRequest.FromString,
            response_serializer=safety__pb2.HealthCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "safety.SafetyService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class SafetyService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckText(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/safety.SafetyService/CheckText",
            safety__pb2.SafetyRequest.SerializeToString,
            safety__pb2.SafetyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Health(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/safety.SafetyService/Health",
            safety__pb2.HealthCheckRequest.SerializeToString,
            safety__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
