# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: safety.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder


# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0csafety.proto\x12\x06safety".\n\rSafetyRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\t"e\n\x0eSafetyResponse\x12\x0c\n\x04safe\x18\x01 \x01(\x08\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x0f\n\x07reasons\x18\x03 \x03(\t\x12\x16\n\x0esanitized_text\x18\x04 \x01(\t\x12\r\n\x05model\x18\x05 \x01(\t"\x14\n\x12HealthCheckRequest"%\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x8e\x01\n\rSafetyService\x12:\n\tCheckText\x12\x15.safety.SafetyRequest\x1a\x16.safety.SafetyResponse\x12\x41\n\x06Health\x12\x1a.safety.HealthCheckRequest\x1a\x1b.safety.HealthCheckResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "safety_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._options = None
    _globals["_SAFETYREQUEST"]._serialized_start = 24
    _globals["_SAFETYREQUEST"]._serialized_end = 70
    _globals["_SAFETYRESPONSE"]._serialized_start = 72
    _globals["_SAFETYRESPONSE"]._serialized_end = 173
    _globals["_HEALTHCHECKREQUEST"]._serialized_start = 175
    _globals["_HEALTHCHECKREQUEST"]._serialized_end = 195
    _globals["_HEALTHCHECKRESPONSE"]._serialized_start = 197
    _globals["_HEALTHCHECKRESPONSE"]._serialized_end = 234
    _globals["_SAFETYSERVICE"]._serialized_start = 237
    _globals["_SAFETYSERVICE"]._serialized_end = 379
# @@protoc_insertion_point(module_scope)
